baseURL = "https://4ndro666.github.io/gptcompendium-site/"
title = "GPT Compendium"
description = "A collection of transcripts of conversations with the OpenAI GPT language model."
theme = "hugo-theme-shell"
languageCode = "en-us"
publishDir = "public"
[permalinks]
  post = "/:year/:month/:day/:slug/"
