# This is a workflow to build and deploy a Hugo site to GitHub Pages
name: Build and Deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Backup index.html before Hugo build
      - name: Backup index.html
        run: cp public/index.html index.html.bak

      # Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Restore index.html after Hugo build
      - name: Restore index.html
        run: cp index.html.bak public/index.html

      # Check index.html hash
      - name: Check index.html hash
        run: |
          echo "Calculating hash of generated index.html..."
          sha256sum -c index.html.sha256

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
