# This is a workflow to build and deploy a Hugo site to GitHub Pages
name: Build and Deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Cache Hugo installation for faster builds
      - name: Cache Hugo
        uses: actions/cache@v4.2.4
        with:
          path: ~/.hugo
          key: ${{ runner.os }}-hugo-${{ hashFiles('config.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      # Step 3: Backup index.html using GitHub Actions artifacts
      - name: Backup index.html
        run: |
          if [ -f public/index.html ]; then
            cp public/index.html index.html.bak
          fi
        continue-on-error: true

      # Step 4: Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 5: Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Step 6: Restore index.html if backup exists
      - name: Restore index.html
        run: |
          if [ -f index.html.bak ]; then
            cp index.html.bak public/index.html
          fi
        continue-on-error: true

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
