name = '4ndr0line'
license = 'MIT'
licenselink = 'https://raw.githubusercontent.com/4ndr0666/4ndr0line/refs/heads/master/LICENSE'
description = 'Cmdline navigation'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/4ndr0666/4ndr0line'

# If the theme has a single author
[author]
  name = '4ndr0666'
  homepage = 'https://github.com/4ndr0666/4ndr0line'
