name = '4ndr0line'
license = 'MIT'
licenselink = 'https://github.com/4ndr0666/4ndr0site/LICENSE'
description = 'Terminal and cmdline output'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/4ndr0666/4ndr0site'

# If the theme has a single author
[author]
  name = '4ndr0666'
  homepage = 'Your website'
